// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContextNodeSummary = { id: string, name: string, nodeType: string, path: string | null, summary: string, depth: number, keywords: Array<string>, };
