// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IndexCompleteNotification = { domain: string, filesProcessed: number, nodesCreated: number, entitiesExtracted: number, processingTimeMs: bigint, };
