// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IndexStatus = { "type": "starting", path: string, } | { "type": "processing", file: string, progress: number, total: number, } | { "type": "analyzing", stage: string, } | { "type": "complete", nodesCreated: number, filesProcessed: number, } | { "type": "error", message: string, };
