#!/bin/zsh

case "${1:-start}" in
  start)
    print "dictation command placeholder: wire this to the transcription capture path next"
    ;;
  *)
    print "usage: dictate start"
    exit 1
    ;;
esac
